services:
  vision-translate:
    image: littleorange666/vision_translate:1.1.3
    restart: on-failure
    ports:
      - "7862:7860"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - MODEL_NAME=translategemma:12b
    extra_hosts:
      - "host.docker.internal:host-gateway"